version: '2'
services:
    timemanagement:
      image: maven
      volumes:
          - ".:/deploy"
      working_dir: "/deploy"
      ports:
          - "8080:8080"
      command: bash -c "./mvnw clean && ./mvnw install && java -jar target/timemanagement-0.0.1-SNAPSHOT.jar"
      container_name: timemanagement
